### ISSUE TITLE
Language code inference doesn't work

### ISSUE THREAD

**Issue by SkyfallWasTaken** [longbridgeapp/rust-i18n#11]
Hi, I updated my project to v1.0.1 of `rust-i18n` and I have a problem after removing the locale code from the files.

Here's a sample file, located at `locales/en.yml`:

```yml
run:
  script-not-found: "the script `%{name}` was not found."
```

However, when I use:
```rust
t!("run.script-not-found", name = "hi")
```

It comes out as `en.run.script-not-found`.

I have to put:
```yml
en:
  run:
    script-not-found: "the script `%{name}` was not found."
```
In order to make it work properly.
