### ISSUE TITLE
Package metadata `default-locale` seems to have no effect

### ISSUE THREAD

**Issue by ChristophB** [longbridgeapp/rust-i18n#22]
Cargo.toml:
```toml
[package.metadata.i18n]
available-locales = ["de", "en"]
default-locale = "de"
```

```rs
use rust_i18n::locale;

#[macro_use]
extern crate rust_i18n;
i18n!("locales");

assert_eq!(locale(), "de"); // => fails!
```
