### ISSUE TITLE
Add to support all translated text in one file better for GitHub Copilot

### ISSUE THREAD

**Issue by huacnlee** [longbridgeapp/rust-i18n#49]
For example:

```yml
welcome:
  en: Welcome to use Rust I18n.
  zh-CN: 欢迎使用 Rust I18n.
  zh-HK: 歡迎使用 Rust I18n.
login:
  en: Login
  zh-CN: 登录
  zh-HK: 登入
```

After that, when we write `en`, the GitHub Copilot or other AI tool will give us a suggestion of other translations.

And we need to support both translation's struct.
