### ISSUE TITLE
Cannot find function `_rust_i18n_translate` in the crate root

### ISSUE THREAD

**Issue by cliftontoaster-reid** [longbridgeapp/rust-i18n#56]
Good morning, I was wondering if I did something wrong, which I'm sure of it. But sadly, I wasn't able to put the finger on what is wrong.
In my main.rs I put 

```rs
#[macro_use]
extern crate rust_i18n;
```

and in main()

```rs
#[tokio::main]
async fn main() {
  // lots of config checking 

  i18n!("locales", fallback = "en");
  
  // and more config
  }
```
  
  but I keep getting
  
![image](https://github.com/longbridgeapp/rust-i18n/assets/42320331/67c32b79-943b-41ed-88f5-259b579c9f3e)

If this can help, this is my src tree. Just in case the file organization was the problem? I don't know, so I put it here.

![image](https://github.com/longbridgeapp/rust-i18n/assets/42320331/95365538-7dc9-47d4-9cc6-e9d93bb34d16)

I hope that someone smarter than me (easy due to only my 2 brain cells) can help me.

Thank you very much for your time.

**Comment by huacnlee** [comment]
Put `i18n!("locales", fallback = "en");` outside of the `main` fn.

**Comment by PatrickMcLennan** [comment]
Hey there, I'm facing the same issue that isn't resolved by the above comment.

Code:

```rust
use wasm_bindgen::prelude::*;
use yew::prelude::*;
use rust_i18n::t;

use components::Header::Header;

rust_i18n::i18n!();

#[function_component(Home)]
pub fn home_view() -> Html {
    html! {
		<>
			<Header />
			<div class="container row">
				<div class="col-6 offset-3">
					<h1>{t!("h1")}</h1>
				</div>
			</div>
		</>
    }
}

#[wasm_bindgen]
pub fn run_home_view() -> Result<(), JsValue> {
    yew::Renderer::<Home>::new().hydrate();
    Ok(())
}
```

Cargo.toml

```toml
[package]
name = "home_view"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "./src/lib.rs"

[dependencies]
components = { path = "./../components" }
rust-i18n = "2.2.1"
wasm-bindgen = "0.2"
yew = { version = "0.21.0", features = ["hydration", "csr", "ssr"] }
```

Folder structure

```
|- locales
|   en.yml
|- src
|   home_view.rs
|   lib.rs
| Cargo.toml
```

Error:

```
error[E0425]: cannot find function `_rust_i18n_translate` in the crate root
  --> views/home_view/./src/home_view.rs:19:11
   |
19 |                     <h1>{t!("h1")}</h1>
   |                          ^^^^^^^^ not found in the crate root
   |
   = note: this error originates in the macro `t` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I'm wondering if this a WASM constraint?  In that maybe rust-i18n doesn't work on WASM?  Would appreciate any guidance!
