### ISSUE TITLE
Single app.yml file doesn't work.

### ISSUE THREAD

**Issue by eminfedar** [longbridgeapp/rust-i18n#60]
I have a single app.yml file in locales folder like this:
```yaml
Settings:
  en: Settings
  tr: Ayarlar
Country:
  en: Country
  tr: Ülke
City:
  en: City
  tr: Şehir
```
I initialized with `i18n!()` and I set the labels of the program like `t!("Settings")`.

But the strings I got on the labels like:
```
en.Settings
en.Country
en.City
```
Which is not I expected:
```
Settings
Country
City
```
Also tried running the app with `LANG=tr_TR.UTF-8 myapp` and I still see `en.Settings` not `tr.Settings` or translated `Ayarlar`.

Also:
The output of the `println!("{:?}", rust_i18n::available_locales!());` is `["app"]`

It seems single file is not supported yet in `version = "2"`
