### ISSUE TITLE
CLI doesn't seem to create TODO.x.yml

### ISSUE THREAD

**Issue by cliftontoaster-reid** [longbridgeapp/rust-i18n#74]
I used this project many times.
Since why, I am creating this issue.

I had forgotten what extensions were used for the YAML, `.yml` or `.yaml`.
So I installed the CLI and tried both with always only one of the list of available locales, but never did it create the appropriate TODO file, and I still wonder why.

Here are the files I created.

`locales/app.yml`
```yaml
_version: 2
introduction:
  en: |
    Welcome! It appears to be your first time using our services. 
    
    It is a pleasure to meet you. 
    
    Before we can collaborate and grant you access to our services, please take the time to review our terms and conditions and privacy policy. 
    
    Before accepting, we recommend reading our policies.
```

`Cargo.toml`
```toml
[package]
name = "purpura_handler"
version = "0.1.0"
edition = "2021"

[package.metadata.i18n]
available-locales = ["en", "de", "es", "fr", "it", "ja", "ko", "pt", "ru", "zh"]
default-locale = "en"

[dependencies]
chrono = { version = "0.4.32", features = ["serde"] }
lapin = { version = "2.3.1", features = ["codegen", "vendored-openssl"] }
rust-i18n = "3.0.1"
scylla = { version = "0.11.1", features = ["chrono", "time"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_yaml = "0.9.30"
serenity = { version = "0.12.0", features = ["full"] }
totp-rs = { version = "5.5.1", features = ["qr", "serde", "zeroize", "rand"] }
tracing = { version = "0.1.40", features = ["async-await"] }
```

Thank you for having read this. 
Have a great day.
